server:
  port: 8081
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spa_salon_spring
    username: postgres
    password: admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher